### ISSUE TITLE
Use Rate Limiting Instead of Random

### ISSUE THREAD

**Issue by jeffreycjohnson** [y2bd/animewasamistake#4]
Currently the bot uses random to determine whether anime was a mistake. It should instead know that anime is always a mistake and just know not to spam the channel by rate limiting itself.

**Comment by y2bd** [comment]
Feature is by design.

**Comment by theloneplant** [comment]
Well the feature is poorly designed, it defeats the intended purpose of the bot

**Comment by y2bd** [comment]
If you feel the feature is poorly designed, you are welcome to submit a PR.

**Comment by theloneplant** [comment]
Maybe I will
